# Generated by Django 5.0.6 on 2024-05-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("workshop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="component",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="computer",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="master",
            options={"ordering": ["number_of_constructed_computers"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="workshop_user_set",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="workshop_user_set",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
