# Generated by Django 5.0.6 on 2024-05-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0002_alter_component_options_alter_computer_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="items",
            new_name="computers",
        ),
        migrations.AddField(
            model_name="cart",
            name="components",
            field=models.ManyToManyField(to="workshop.component"),
        ),
    ]
