# Generated by Django 5.0.6 on 2024-05-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0003_rename_items_cart_computers_cart_components"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="components",
            field=models.ManyToManyField(related_name="carts", to="workshop.component"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="computers",
            field=models.ManyToManyField(related_name="carts", to="workshop.computer"),
        ),
    ]
