# Generated by Django 5.0.6 on 2024-05-19 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0004_alter_cart_components_alter_cart_computers"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workshop.master",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="components",
            field=models.ManyToManyField(
                blank=True, related_name="carts", to="workshop.component"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="computers",
            field=models.ManyToManyField(
                blank=True, related_name="carts", to="workshop.computer"
            ),
        ),
    ]
