# Generated by Django 5.0.6 on 2024-05-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0005_cart_master_alter_cart_components_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_client",
            field=models.BooleanField(default=True),
        ),
    ]
